language: node_js
node_js:
  - "10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - nsis
      - p7zip-full

install:
  - npm install
script: 
  - npm run dist